config-version = 2

after-startup-command = [
    'exec-and-forget borders active_color=0xcc66cc66 inactive_color=0x00494d64 width=7',
    'exec-and-forget $HOME/.config/aerospace/layout-3columns.sh',
]

start-at-login = true

automatically-unhide-macos-hidden-apps = false

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = true

default-root-container-layout = 'tiles'
default-root-container-orientation = 'horizontal'

accordion-padding = 30

on-focus-changed = ['move-mouse window-lazy-center']
on-mode-changed = []

persistent-workspaces = ["1", "2", "3", "4", "5", "6", "7", "8", "9"]

[gaps]
    inner.horizontal = 10
    inner.vertical =   10
    outer.left =       10
    outer.bottom =     5
    outer.top =        5
    outer.right =      10

[workspace-to-monitor-force-assignment]
    9 = '^built-in retina display$'

[mode.main.binding]
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    alt-h = 'focus left --boundaries all-monitors-outer-frame'
    alt-j = 'focus down --boundaries all-monitors-outer-frame'
    alt-k = 'focus up --boundaries all-monitors-outer-frame'
    alt-l = 'focus right --boundaries all-monitors-outer-frame'

    alt-shift-h = 'move left --boundaries all-monitors-outer-frame --boundaries-action stop'
    alt-shift-j = 'move down --boundaries all-monitors-outer-frame --boundaries-action stop'
    alt-shift-k = 'move up --boundaries all-monitors-outer-frame --boundaries-action stop'
    alt-shift-l = 'move right --boundaries all-monitors-outer-frame --boundaries-action stop'
    alt-cmd-shift-h = 'join-with left'
    alt-cmd-shift-j = 'join-with down'
    alt-cmd-shift-k = 'join-with up'
    alt-cmd-shift-l = 'join-with right'

    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'
    alt-shift-minus = 'resize smart -500'
    alt-shift-equal = 'resize smart +500'
    alt-i = ['balance-sizes', 'resize smart +500']

    alt-f1 = 'exec-and-forget $HOME/.config/aerospace/layout-1column.sh'
    alt-f2 = 'exec-and-forget $HOME/.config/aerospace/layout-2columns.sh'
    alt-f3 = 'exec-and-forget $HOME/.config/aerospace/layout-3columns.sh'

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'

    alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
    alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
    alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
    alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
    alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
    alt-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
    alt-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
    alt-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
    alt-shift-9 = ['move-node-to-workspace 9', 'workspace 9']

    alt-f = 'layout floating tiling'
    alt-m = 'fullscreen'

    alt-backtick = 'exec-and-forget bash -c "if [ -f /tmp/aerospace-borders-off ]; then borders active_color=0xcc66cc66 inactive_color=0x00494d64 width=7; rm /tmp/aerospace-borders-off; else borders width=0; touch /tmp/aerospace-borders-off; fi"'

    alt-tab = 'workspace-back-and-forth'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
